# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-f33c6afe-95a1-4986-9e73-3f66969d7104";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-f33c6afe-95a1-4986-9e73-3f66969d7104".device =
    "/dev/disk/by-uuid/f33c6afe-95a1-4986-9e73-3f66969d7104";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8689-2904";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/HDD" = {
    device = "/dev/disk/by-uuid/90835689-3b0e-4d82-ac88-48f20ea8de95";
    fsType = "ext4";
  };

  fileSystems."/mnt/SecondSSD" = {
    device = "/dev/disk/by-uuid/8f0d255a-45e7-49bc-b8b4-59202ce88ae2";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/mapper/luks-4f6640dc-82c0-4052-bda3-24857e2d56f0"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
