# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, inputs, ... }:

{
  imports =
    [
      ./hardware-configuration.nix # Generated by hardware-scan
    ../../modules/core # Import shared core config
    ../../modules/desktop/gnome.nix # This is a desktop machine
    ];


  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-ce879d3b-85ba-437e-acd1-6cda02f2f75b".device = "/dev/disk/by-uuid/ce879d3b-85ba-437e-acd1-6cda02f2f75b";
  networking.hostName = "nixos-laptop"; # Define your hostname.

  nixpkgs.overlays = [
    inputs.nur.overlays.default
  ];

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.andrew = {
    isNormalUser = true;
    description = "andrew";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
 
    ];
  };

  system.stateVersion = "25.11";


}
