# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c8102d97-874b-4069-8c3f-4f35b0875ebf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c8102d97-874b-4069-8c3f-4f35b0875ebf".device = "/dev/disk/by-uuid/c8102d97-874b-4069-8c3f-4f35b0875ebf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D5EA-C7C8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ce879d3b-85ba-437e-acd1-6cda02f2f75b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
