# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  config,
  pkgs,
  inputs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix # Generated by hardware-scan
    ../../modules/core # Import shared core config
    ../../modules/desktop/gnome.nix # This is a desktop machine
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-d078ae3c-7485-430f-bc81-e9c6d645086f".device =
    "/dev/disk/by-uuid/d078ae3c-7485-430f-bc81-e9c6d645086f";
  networking.hostName = "nixos-desktop"; # Define your hostname.

  nixpkgs.overlays = [
    inputs.nur.overlays.default
  ];

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.andrew = {
    isNormalUser = true;
    description = "andrew";
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    packages = with pkgs; [

    ];
  };

  # nvidia
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.open = true;

  system.stateVersion = "25.11";
}
