# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{
  config,
  pkgs,
  inputs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix # Generated by hardware-scan
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices."luks-d078ae3c-7485-430f-bc81-e9c6d645086f".device =
    "/dev/disk/by-uuid/d078ae3c-7485-430f-bc81-e9c6d645086f";
  networking.hostName = "nixos-desktop"; # Define your hostname.

  # nvidia
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia.open = true;

  system.stateVersion = "25.11";
}
