# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "usbcore.autosuspend=-1" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7d337d26-60f6-440e-b2ff-35815c2cfd4c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7d337d26-60f6-440e-b2ff-35815c2cfd4c".device = "/dev/disk/by-uuid/7d337d26-60f6-440e-b2ff-35815c2cfd4c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1F79-EF04";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d078ae3c-7485-430f-bc81-e9c6d645086f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
