{ inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix # Generated by hardware-scan
    ../../modules/core # Import shared core config
    ../../modules/desktop/gnome.nix # This is a desktop machine
  ];

  nixpkgs.overlays = [
    inputs.nur.overlays.default
  ];

  networking.hostName = "nixos-vm";

  # Host specific bootloader
  boot.loader.grub = {
    enable = true;
    device = "nodev";
  };

  # Host specific virtualization
  virtualisation.vmware.guest.enable = true;

  # Define the User
  users.users.andrew = {
    isNormalUser = true;
    extraGroups = [
      "networkmanager"
      "wheel"
    ];
    packages = [ ];
  };

  # System state version
  system.stateVersion = "24.11";
}
