{ inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix # Generated by hardware-scan
  ];

  networking.hostName = "nixos-vm";

  # Host specific bootloader
  boot.loader.grub = {
    enable = true;
    device = "nodev";
  };

  # Host specific virtualization
  virtualisation.vmware.guest.enable = true;

  # System state version
  system.stateVersion = "24.11";
}
