{ config, pkgs, ... }:

let
  tofuAuthentikScript = pkgs.writeShellScriptBin "tofu-authentik" ''
    set -e
    # Load secrets
    if [ -f "${config.sops.secrets.authenik_env.path}" ]; then
      set -a
      source "${config.sops.secrets.authenik_env.path}"
      set +a
    fi

    # Export variables for Terraform
    export TF_VAR_authentik_api_token="$AUTHENTIK_BOOTSTRAP_TOKEN"

    # Set working directory
    # We use a fixed path here as requested by the user's setup
    cd /home/andrew/nixos-config/terraform/authentik

    # Execute OpenTofu
    echo "Executing OpenTofu in $(pwd)..."
    exec ${pkgs.opentofu}/bin/tofu "$@"
  '';
in
{

  imports = [
    ./nginx.nix
  ];
  services.authentik = {
    enable = true;
    environmentFile = config.sops.secrets.authenik_env.path;
    settings = {
      email = {
        host = "smtp.hsr.wtf";
        port = 587;
        username = "authentik@hsr.wtf";
        use_tls = true;
        use_ssl = false;
        from = "authentik@hsr.wtf";
      };
      disable_startup_analytics = true;
      avatars = "initials";
    };
  };

  # Ensure the script is available in the path
  environment.systemPackages = [ tofuAuthentikScript ];

  # Ensure Authentik is running before applying terraform
  # Run OpenTofu on rebuild to ensure state is up to date for dependents
  systemd.services.authentik-terraform-apply = {
    description = "Apply Authentik Terraform Configuration";
    wantedBy = [ "multi-user.target" ];
    wants = [ "authentik.service" ];
    after = [ "authentik.service" ];
    before = [
      "netbird-management.service"
      "netbird-dashboard.service"
    ];
    serviceConfig = {
      # Type = "oneshot";
      # ExecStart is generated by 'script' below
      Type = "oneshot";
    };
    script = ''
      # Wait for Authentik to be ready
      echo "Waiting for Authentik at https://127.0.0.1:9443..."
      until ${pkgs.curl}/bin/curl --fail --silent --insecure --max-time 5 https://127.0.0.1:9443/-/health/live/; do
        echo "Authentik not ready. Retrying in 2 seconds..."
        sleep 2
      done
      echo "Authentik is ready! Applying Terraform..."
      # Initialize OpenTofu (downloads providers, creates lock file if needed)
      ${tofuAuthentikScript}/bin/tofu-authentik init -upgrade
      # Apply configuration
      ${tofuAuthentikScript}/bin/tofu-authentik apply -auto-approve
    '';
  };

}
